# The name of the environment matching the repository name
name: sfg2d
# I prefer conda-forge packages for my projects
channels:
  - javascript
  - conda-forge
  - defaults
# Start with Python and include everything you need
dependencies:
- python=3.7
- pip=19.3.1
- numpy=1.17.3
- pandas=0.25.2
- matplotlib=3.1.1
- scipy=1.3.1
- seaborn=0.9.0
- pillow=6.2.1
- ipython=7.9.0
- jupyter=1.0.0
- jupyterlab=1.1.4
- xmltodict=0.12.0
- pyyaml=5.1.2
- notebook=6.0.2
- widgetsnbextension=3.5.1
- ipywidgets=7.5.1
- iminuit=1.3.7
- gitpython=3.0.2
- ipympl=0.3.3
- altair=3.2.0
- selenium=3.141.0
- nodejs=10.13.0
- python-chromedriver-binary=79.0.3945.16.0
- geckodriver==0.26.0
- pip:
  - cairosvg==2.4.2
  - uncertainties==3.1.2
  - dpath==1.4.2
  - chromedriver==2.24.1
  - numpy-indexed==0.3.5
  - https://github.com/deisi/SFG2D/blob/master/dist/sfg2d-0.6.0-py3-none-any.whl?raw=true
